!Config
  APP_NAME: "meloetta"
  DESCRIPTION: "Music bot for the /r/Pokemon Discord server."

  PREFIXES: 
    - !ENV "PREFIX"

  TOKEN: !ENV "TOKEN"

  COGS:
    "bot.cogs.core.git": ~

    "bot.cogs.player": !Config

      DEFAULT_ALBUM_ARTWORK: "res/unknown.png"
      DEFAULT_VOLUME: 0.1
      DEFAULT_PLAYLIST_DIRECTORY: "res/mp3/"

      INSTANCES:

        - !Config # - Test Server
          voice_channel: !Channel 551765961070608384 551765961070608388
          log_channel: !Channel 551765961070608384 551766646692380692

