# Meloetta Configuration File
!Config
  BOT: !Config
    PREFIX: '!;'
    TOKEN: !ENV BOT_TOKEN

  LOGGING: !Config
    LOG_LEVEL: "INFO"

  EXTENSIONS:
    jishaku: ~

    cogs.player: !Config
      LAVALINK: !Config
        HOSTNAME: !ENV LAVALINK_HOSTNAME
        PASSWORD: !ENV LAVALINK_PASSWORD
      DEFAULT_VOLUME: 10
      MAX_SEARCH_RESULTS: 5
