!Config
  APP_NAME: "meloetta"
  DESCRIPTION: "Music bot for the /r/Pokemon Discord server."

  PREFIXES: 
    - !ENV "PREFIX"

  TOKEN: !ENV "TOKEN"

  COGS:
    "bot.cogs.core.git": ~

    "bot.cogs.player": !Config

      DEFAULT_VOLUME: 0.1

      INSTANCES:

        - !Config # - Test Server
          voice_channel: !Channel 229563119582576641 288670665731735553
          log_channel: !Channel 229563119582576641 291528730881556490

        