[tool.poetry]
name = "discord-mod-bot"
version = "0.0.1"
description = ""
authors = ["/u/Haruka-sama"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
websockets = "6.0"
pyyaml = "^5.3.1"
mutagen = "^1.44.0"
psutil = "^5.7.0"
python-Levenshtein = "^0.12.0"
fuzzywuzzy = "^0.18.0"
uvloop = {version = "^0.14.0", markers = "sys_platform == 'linux'"}
"discord.py" = {git = "https://github.com/bijij/discord.py.git", rev = "feature-voiceclient-cleanup"}
discord-ext-menus = {git = "https://github.com/Rapptz/discord-ext-menus.git"}
youtube-dl = "^2020.3.24"

[tool.poetry.extras]
"discord.py" = ["voice"]

[tool.poetry.dev-dependencies]
"autopep8" = "^1.5"
"flake8" = "^3.7.9"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"